package ar.gob.msal.sisa.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import lombok.Getter;
import lombok.Setter;

@Entity(name="RES_RESIDENTE")
public class Residente {

	@Id
	@Column(name="ID_RES_RESIDENTE")
	@Getter
	@Setter
	private long id;
	

	@Column(name="NOMBRE")
	@Getter
	@Setter
	private String nombre;

	@Column(name="APELLIDO")
	@Getter
	@Setter
	private String apellido;

	@Column(name="ID_TIPODOC")
	@Getter
	@Setter
	private long tipodoc;


	@Column(name="NRODOC")
	@Getter
	@Setter
	private long ndoc;
	

//	ID_ESTADO_CIVIL	NUMBER(1,0)
//	ID_PROVINCIA_RESIDENCIA	NUMBER(2,0)
	

	@Column(name="ID_PAIS_NACIMIENTO")
	@Getter
	@Setter
	private long paisnacimiento;
	
//	ID_LOCALIDAD_RESIDENCIA	NUMBER(10,0)
//	ID_PROVINCIA_NACIMIENTO	NUMBER(2,0)
//	FECHA_NACIMIENTO	DATE
//	CALLE	VARCHAR2(200 BYTE)
//	CALLE_NRO	VARCHAR2(10 BYTE)
//	CALLE_PISO	VARCHAR2(10 BYTE)
//	CALLE_DPTO	VARCHAR2(10 BYTE)
//	CP	VARCHAR2(8 BYTE)
//	EMAIL	VARCHAR2(100 BYTE)
//	ID_PROFESION	NUMBER(3,0)
//	ID_INSTITUCION_FORMADORA	NUMBER(5,0)
//	PROMEDIO	NUMBER(4,2)
//	ID_ESPEC_REFES_CONCURSO	NUMBER(9,0)
//	ID_PROVINCIA_CONCURSO	NUMBER(2,0)
//	ID_SEDE_PROVINCIA	NUMBER(2,0)
//	PUNTAJE_EXAMEN	NUMBER(5,2)
//	PUNTAJE_ENTREVISTA	NUMBER(5,2)
//	PUNTAJE_ANTECEDENTES	NUMBER(5,2)
//	PUNTAJE_FINAL	NUMBER(5,2)
//	ID_ESTABLECIMIENTO_ADJ	NUMBER(6,0)
//	ID_ESPEC_REFES_ADJ	NUMBER(9,0)
//	ID_PROVINCIA_2DA_ADJ	NUMBER(2,0)
//	ID_ESPEC_REFES_2DA_ADJ	NUMBER(9,0)
//	ID_RES_ESTADO_RESIDENTE	NUMBER(2,0)
//	ID_PROFESIONAL	NUMBER(11,0)
//	ID_RES_PREINSCRIPCION	NUMBER(4,0)
//	ID_RES_PREINSCRIPCION_2DA	NUMBER(4,0)
//	NYC	VARCHAR2(2 BYTE)
	
//	SEXO	VARCHAR2(1 BYTE)
//	@Column(name="SEXO")
//	@Getter
//	@Setter
//	private String sexo;
	
//	FECHA_TITULO	DATE
//	TITULO_TRAMITE	VARCHAR2(2 BYTE)
//	COMENTARIO	VARCHAR2(2000 BYTE)
//	TE1	VARCHAR2(40 CHAR)
//	TE2	VARCHAR2(40 CHAR)
//	ID_TIPO_TE1	NUMBER(2,0)
//	ID_TIPO_TE2	NUMBER(2,0)
//	ID_NACIONALIDAD	NUMBER(3,0)
//	OBSERVACIONES_RESULTADO	VARCHAR2(2000 CHAR)
//	VACANTE_ADJUDICADA	VARCHAR2(2 CHAR)
//	OTROS_PUNTAJES1	VARCHAR2(200 CHAR)
//	OTROS_PUNTAJES2	VARCHAR2(200 CHAR)
//	REALIZO_ENTREVISTA	VARCHAR2(2 CHAR)
//	ORDEN_MERITO	NUMBER(4,0)
//	ORDEN_MERITO_2DA	NUMBER(4,0)
//	PUNTAJE_ENTREVISTA_2DA	NUMBER(5,2)
//	PUNTAJE_ANTECEDENTES_2DA	NUMBER(5,2)
//	PUNTAJE_FINAL_2DA	NUMBER(5,2)
//	REALIZO_ENTREVISTA_2DA	VARCHAR2(2 CHAR)
//	FECHA_REGISTRO	DATE
//	FECHA_MODIFICACION	DATE
//	ID_USUARIO_REGISTRO	NUMBER(6,0)
//	ID_USUARIO_MODIFICACION	NUMBER(6,0)
//	ID_INTERFAZ_REGISTRO	NUMBER(2,0)
//	ID_INTERFAZ_MODIFICACION	NUMBER(2,0)
//	PASSWORD	VARCHAR2(10 BYTE)
//	ID_SEDE_LOCALIDAD	NUMBER(10,0)
//	CANTIDAD_HIJOS	NUMBER(2,0)
//	ID_REFES_ESPECIALIDAD_PRO	NUMBER(5,0)
//	ID_INSTITUCION_FORMADORA_PRO	NUMBER(5,0)
//	FECHA_EGRESO	DATE
//	ID_INSTITUCION_FORMADORA_CONC	NUMBER(5,0)
//	PUNTAJE_NYC	NUMBER(5,2)
//	PUNTAJE_IDIOMA	NUMBER(5,2)
//	ID_INSTITUCION_FORMADORA_2DA	NUMBER(5,0)
//	FECHA_INICIO_RESIDENCIA	DATE
//	FECHA_RENUNCIA	DATE
//	MOTIVO_RENUNCIA	VARCHAR2(2000 CHAR)
//	TOMA_CARGO	VARCHAR2(2 CHAR)
//	CUIL	NUMBER(11,0)
//	ID_INSTITUCION_FORMADORA_ADJ	NUMBER(5,0)
//	PROMEDIO_ACADEMICO	NUMBER(5,2)
//	FECHA_INICIO_CONTRADO	DATE
//	FECHA_FIN_CONTRATO	DATE
//	MATRICULA	NUMBER(10,0)
//	SUELDO	NUMBER(8,2)
//	REVISADO	VARCHAR2(2 CHAR)
//	PUNTAJE_NYC_2DA	NUMBER(5,2)
//	PUNTAJE_IDIOMA_2DA	NUMBER(5,2)
//	VACANTE_ADJUDICADA_2DA	VARCHAR2(2 BYTE)
//	FECHA_INICIO_RES_2DA	DATE
//	FECHA_RENUNCIA_2DA	DATE
//	MOTIVO_RENUNCIA_2DA	VARCHAR2(2000 BYTE)
//	TOMA_CARGO_2DA	VARCHAR2(2 BYTE)
//	ID_INSTITUCION_FORM_ADJ_2DA	NUMBER(5,0)
//	FECHA_INICIO_CONTRADO_2DA	DATE
//	FECHA_FIN_CONTRATO_2DA	DATE
//	MATRICULA_2DA	NUMBER(10,0)
//	SUELDO_2DA	NUMBER(8,2)
//	REVISADO_2DA	VARCHAR2(2 BYTE)
//	NRO_MESA	NUMBER(2,0)
//	ID_TIPO_CUPO	NUMBER(3,0)
//	ID_TIPO_CUPO_2DA	NUMBER(3,0)
//	ID_RES_PREINSCRIPCION_BKP	NUMBER(4,0)
//	ID_PROVINCIA_2DA_BKP	NUMBER(2,0)
//	ID_INSTITUCION_FORMADORA_BKP	NUMBER(5,0)
//	ID_ESPEC_REFES_2DA_BKP	NUMBER(5,0)
//	PUNTAJE_FINAL_BKP	NUMBER(5,2)
//	ORDEN_MERITO_BKP	NUMBER(5,2)
//	VACANTE_ADJUDICADA_BKP	VARCHAR2(2 CHAR)
//	ID_INSTITUCION_FORM_ADJ_BKP	NUMBER(5,0)
//	ID_TIPO_CUPO_BKP	NUMBER(3,0)
//	FECHA_RENUNCIA_BKP	DATE
//	EMAIL2	VARCHAR2(100 CHAR)
//	NOTA_APELADA	NUMBER(5,2)
//	FECHA_HAB	DATE
//	TIPO_MATRICULA	VARCHAR2(2 CHAR)
//	FECHA_CASAMIENTO	DATE
//	INGRESO_CARRERA	NUMBER(4,0)
//	CODIGO_AREA	VARCHAR2(10 CHAR)
//	APRUEBA_ENTREVISTA	VARCHAR2(2 CHAR)
//	CODIGO_AREA_TE2	VARCHAR2(10 CHAR)
//	ID_ESPEC_REFES_ADJ_2DA	NUMBER(9,0)
	
}
